plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - sorbet/**/*.rbi

# Standard naming for RuboCop extension gems
Naming/FileName:
  Exclude:
    - lib/rubocop-sane.rb

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Lint/EmptyFile:
  Enabled: true

Metrics/AbcSize:
  Max: 20
  Exclude:
    - lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 150
  Exclude:
    - lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb

Naming/PredicatePrefix:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

Style/ClassVars:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  EnforcedStyle: brackets

Style/NumericPredicate:
  Enabled: false
